# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_text',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
